config/routes.rb
Potofgold::Application.routes.draw do

  resources :images

  resources :coupons

  resources :deals

  root :to => 'pages#home'
  get '/auth/twitter/callback' => 'sessions#create'
  delete '/signout' => 'sessions#destroy', as: :signout
  get '/deal_stats/:id' => 'deals#stats', as: :deal_stats
  post '/tweet' => 'deals#tweet', as: :tweet
  get 'advertiser_sign_in' => 'sessions#advertiser_sign_in'

  post '/redeem/:id' => 'coupons#redeem', as: :redeem

end

app/models/advertiser.rb
class Advertiser < ActiveRecord::Base
  attr_accessible :image_url, :uid, :username, :business_name, :followers_count
  
  #Associations
  has_many :deals
  has_many :images
  
  #Class Method
  def self.find_or_create_from_auth_hash(auth_hash)
    auth_hash['extra']['raw_info']['followers_count']
    advertiser = self.find_by_uid(auth_hash['uid'])
    unless advertiser
      advertiser = self.create(image_url: auth_hash['info']['image'], uid: auth_hash['uid'], 
                              username: auth_hash['info']['nickname'], business_name: auth_hash['info']['name'],
                              followers_count: auth_hash['extra']['raw_info']['followers_count'])             
    end
    advertiser
  end

  #Instance Method

  def advertiser?
    true
  end

  def user?
    false
  end
  
  def not_create_deal?(deal_id)
    !self.deals.map { |d| d.id }.index(deal_id.to_i)
  end
  
end

app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

app/views/advertisers/_form.html.erb
<%= form_for(@advertiser) do |f| %>
  <% if @advertiser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertiser.errors.count, "error") %> prohibited this advertiser from being saved:</h2>

      <ul>
      <% @advertiser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advertisers/edit.html.erb
<h1>Editing advertiser</h1>

<%= render 'form' %>

<%= link_to 'Show', @advertiser %> |
<%= link_to 'Back', advertisers_path %>

app/views/advertisers/index.html.erb
<h1>Listing advertisers</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Uid</th>
    <th>Image url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @advertisers.each do |advertiser| %>
  <tr>
    <td><%= advertiser.username %></td>
    <td><%= advertiser.uid %></td>
    <td><%= advertiser.image_url %></td>
    <td><%= link_to 'Show', advertiser %></td>
    <td><%= link_to 'Edit', edit_advertiser_path(advertiser) %></td>
    <td><%= link_to 'Destroy', advertiser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Advertiser', new_advertiser_path %>

app/views/advertisers/new.html.erb
<h1>New advertiser</h1>

<%= render 'form' %>

<%= link_to 'Back', advertisers_path %>

app/views/advertisers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @advertiser.username %>
</p>

<p>
  <b>Uid:</b>
  <%= @advertiser.uid %>
</p>

<p>
  <b>Image url:</b>
  <%= @advertiser.image_url %>
</p>


<%= link_to 'Edit', edit_advertiser_path(@advertiser) %> |
<%= link_to 'Back', advertisers_path %>