config/routes.rb
Potofgold::Application.routes.draw do

  resources :images

  resources :coupons

  resources :deals

  root :to => 'pages#home'
  get '/auth/twitter/callback' => 'sessions#create'
  delete '/signout' => 'sessions#destroy', as: :signout
  get '/deal_stats/:id' => 'deals#stats', as: :deal_stats
  post '/tweet' => 'deals#tweet', as: :tweet
  get 'advertiser_sign_in' => 'sessions#advertiser_sign_in'

  post '/redeem/:id' => 'coupons#redeem', as: :redeem

end

app/models/deal.rb
class Deal < ActiveRecord::Base

  attr_accessible :advertiser_id, :coupon_text, :end_date, :sample_tweet, :description, :image_id
  
  #Associations
  belongs_to :advertiser
  has_many :coupons
  has_many :users, through: :coupons
  belongs_to :image
  
  #Validation
  validates :end_date, :coupon_text, :sample_tweet, :description, :image_id, presence: true
  
  #Instance methods
  def redemptions
    self.coupons.redeemed.length
  end
  
  def followers_array
    self.coupons.any? ? self.coupons.map { |c| c.followers } : [0]
  end
  
  def followers
    new_followers = self.coupons.any? ? self.coupons.map { |c| c.followers }.total : 0
    self.advertiser.followers_count + new_followers
  end
  
  def conversion
    self.coupons.length > 0 ? self.coupons.redeemed.length.to_f / self.coupons.length.to_f * 100.0 : 0
  end
  
  def expired?
    self.end_date < DateTime.now()
  end
  
  def not_expired?
    self.end_date >= DateTime.now()
  end
  
  def referrals
    self.coupons.referrals.length
  end
  
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  before_filter :check_current_authorized_user_is_an_advertiser, except: [:show]
  before_filter :check_current_authorized_user_created_deal, only: [:show]

  # GET /deals
  # GET /deals.json
  def index
    @deals = current_authorized_user.deals.includes(:coupons).order('end_date ASC')
    @deals_total_followers = @deals.map { |d| d.followers }.total

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
    @deal = Deal.find(params[:id], include: [:advertiser, :coupons, :users, :image])
    session[:referred] = true if params[:referred]
    session[:deal_id] = @deal.id unless current_authorized_user
    @coupon = @deal.coupons.for_user(current_authorized_user).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end

  def stats
    @deal = Deal.find(params[:id], include: [:advertiser, :coupons, :users])

    grouped_coupons = @deal.coupons.oldest.group_by { |c| c.created_at.strftime('%D') }
    prev = 0
    arr = grouped_coupons.values.map { |coupons| coupons.map { |c| c.followers}.total }.collect { |value| prev += value }

    @h = LazyHighCharts::HighChart.new('graph', style: '') do |f|
      f.options[:title][:text] = 'Who\'s seen it?'
      f.options[:legend][:enabled] = false
      f.options[:chart][:defaultSeriesType] = "area"
      f.options[:plotOptions] = {areaspline: {pointStart: @deal.created_at }}
      f.options[:xAxis][:type] = "datetime"
      f.series(:name=>'Followers', :data=> arr)
    end
  end

  # GET /deals/new
  # GET /deals/new.json
  def new
    @deal = Deal.new
    @images = current_authorized_user.images
    @default_images = Image.order('created_at ASC').limit(6)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
    @images = current_authorized_user.images
    @default_images = Image.order('created_at ASC').limit(6)
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = current_authorized_user.deals.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.json { render json: @deal }
      else
        format.json { render json: { error: 'There was an error!' } }
      end
    end
  end

  # POST /tweet
  def tweet
    TwitterMessaging.new(session[:token], session[:secret]).send_tweet(params[:tweet])

    redirect_to deals_url, notice: 'You just started a new deal. Good luck!'

  end

  # PUT /deals/1
  # PUT /deals/1.json
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        @images = current_authorized_user.images
        @default_images = Image.order('created_at ASC').limit(6)
        format.html { render action: "edit", alert: 'Deal not updated!' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end

  private

    def check_current_authorized_user_is_an_advertiser
      redirect_to root_url unless current_authorized_user.advertiser?
    end

    def check_current_authorized_user_created_deal
      if current_authorized_user
        redirect_to root_url if current_authorized_user.advertiser? && current_authorized_user.not_create_deal?(params[:id])
      end
    end

end

app/helpers/deals_helper.rb
module DealsHelper

  def s3_uploader_form(options = {}, &block)
    uploader = S3Uploader.new(options)
    form_tag(uploader.url, uploader.form_options) do
      uploader.fields.map do |name, value|
        hidden_field_tag(name, value)
      end.join.html_safe + capture(&block)
    end
  end

  class S3Uploader
    def initialize(options)
      @options = options.reverse_merge(
        id: "fileupload",
        aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
        bucket: ENV["AWS_S3_BUCKET"],
        acl: "public-read",
        expiration: 10.hours.from_now,
        max_file_size: 500.megabytes,
        as: "file"
      )
    end

    def form_options
      {
        id: @options[:id],
        method: "post",
        authenticity_token: false,
        multipart: true,
        data: {
          post: @options[:post],
          as: @options[:as]
        }
      }
    end

    def fields
      {
        :key => key,
        :acl => @options[:acl],
        :policy => policy,
        :signature => signature,
        "AWSAccessKeyId" => @options[:aws_access_key_id],
      }
    end

    def key
      @key ||= "uploads/#{SecureRandom.hex}/${filename}"
    end

    def url
      "https://#{@options[:bucket]}.s3.amazonaws.com/"
    end

    def policy
      Base64.encode64(policy_data.to_json).gsub("\n", "")
    end

    def policy_data
      {
        expiration: @options[:expiration],
        conditions: [
          ["starts-with", "$utf8", ""],
          ["starts-with", "$key", ""],
          ["content-length-range", 0, @options[:max_file_size]],
          {bucket: @options[:bucket]},
          {acl: @options[:acl]}
        ]
      }
    end

    def signature
      Base64.encode64(
        OpenSSL::HMAC.digest(
          OpenSSL::Digest::Digest.new('sha1'),
          @options[:aws_secret_access_key], policy
        )
      ).gsub("\n", "")
    end
  end

end

app/views/deals/_background.html.erb
<p>Select your background image by one of the following ways:</p>
<ol>
    <%= s3_uploader_form post: images_url, as: "image[image_url]" do %>
      <li>
        <span>Upload an image: </span>
        <%= file_field_tag :file, multiple: true %>
      </li>
    <% end %>
<script id="template-upload" type="text/x-tmpl">
  <div class="upload">
    {%=o.name%}
    <div class="progress" style="width: 95%; margin-left: 15px;"><div class="bar" style="width: 0%"></div></div>
  </div>
</script>
</p>
<% if @images.any? %>
  <li>
    <span>Or use a picture you've already uploaded: </span>
<% end %>
  <ul class="images_to_select">
    <% if @images.any? %>
      <% @images.each do |image| %>
        <li class="pull-left">
          <%= image_tag image.image_url, id: "bg_image_#{image.id}" %>
          <p><%= link_to 'Preview', '#', class: 'preview' %> | <%= link_to 'Select', '#', class: 'select' %></p>
        </li>
      <% end %>
    <% end %>
  </ul>
</li>
  <li>
    <span>Don't have a great pic? No worries. Use one of ours. </span>
    <ul class="images_to_select">
      <% @default_images.each do |image| %>
      <li class="pull-left">
        <%= image_tag image.image_url, id: "bg_image_#{image.id}" %>
        <p><%= link_to 'Preview', '#', class: 'preview' %> | <%= link_to 'Select', '#', class: 'select' %></p>
      </li>
      <% end %>
    </ul>
  </li>
  </ol>
</div>
<% if action_name != 'edit' %>
  <div class="deal_details_container hide">
  	<div class="deal_inner deal_details">
      <h1><%= current_authorized_user.business_name %></h1>
      <%= render 'form' %>
  	</div>
  	<div class="deal_inner hide deal_starter_tweet">
  	  <p>Congrats, your deal is now live! Send a tweet to your followers to let them know about the deal.</p>
  	  <%= form_tag(tweet_url) do %>
      <%= text_area_tag :tweet, nil, rows: '6', class: 'deal_description', placeholder: 'Enter starter tweet' %>
      <p><span class="countdown_tweet">140</span></p>
      <%= submit_tag 'Tweet to start the deal!', class: 'orange_btn', id: 'tweet_button' %>
    <% end %>
  </div>
<% end %>

app/views/deals/_form.html.erb
<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <p class="red"><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</p>
      <% @deal.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
      <br/>
    </div>
  <% end %>
  <div class="field offer">
    <%= f.label :your_offer %>
    <%= f.text_field :coupon_text, class: 'offer_text', placeholder: 'Free Appetizer' %>
  </div>
  <div class="field description">
    <%= f.label :description_of_your_offer %>
    <%= f.text_area :description, rows: '6', class: 'deal_description', placeholder: 'Come in to our resturant for a free appetizer...' %>
  </div>
  <div class="field date">
    <%= f.label :offer_end_date %>
    <%= f.text_field :end_date, placeholder: 'When is your offer valid until', class: 'deal_end_date' %>
  </div>
  <div class="field">
    <%= f.label :suggested_tweet_for_your_customers_to_share %>
    <p class="explain_label">Your customer will tweet this to get your offer.<br>
                              A link to the deal will be added to the end of the tweet.</p>
    <%= f.text_area :sample_tweet, rows: '6', class: 'deal_tweet', placeholder: 'Enter a tweet for your customers to share' %>
    <p><span class="countdown_deal_sample_tweet">140</span>
  </div>
  <%= f.hidden_field :image_id %>
  <div class="actions">
    <% if action_name != 'edit' %>
      <%= f.submit 'Start Deal', id: 'start_deal' %>
    <% else %>
      <%= f.submit 'Update Deal' %>
    <% end %>
  </div>
<% end %>

<script>

  $(function(){
    function updateCountdown() {
      // 140 is the max message length
      var remaining = 140 - $('#tweet').val().length;
      if (remaining <= 10){
        $('.countdown_tweet').css('color', 'red');
      }
      else {
        $('.countdown_tweet').css('color', 'white');
      }
      if (remaining < 0){
        $('#tweet_button').attr('disabled', true);
      }
      else {
        $('#tweet_button').attr('disabled', false);
      }
      $('.countdown_tweet').text(remaining);
    }

    function updateCountdownSample() {
      // 120 is the max message length
      var remaining = 120 - $('#deal_sample_tweet').val().length;
      if (remaining <= 10){
        $('.countdown_deal_sample_tweet').css('color', 'red');
      }
      else {
        $('.countdown_deal_sample_tweet').css('color', 'white');
      }
      if (remaining < 0){
        $('#start_deal').attr('disabled', true);
      }
      else {
        $('#start_deal').attr('disabled', false);
      }
      $('.countdown_deal_sample_tweet').text(remaining);
    }

    updateCountdownSample();
    <% if action_name != 'edit' %>
      updateCountdown();
      $('#tweet').change(updateCountdown);
      $('#tweet').keyup(updateCountdown);
    <% end %>
    $('#deal_sample_tweet').change(updateCountdownSample);
    $('#deal_sample_tweet').keyup(updateCountdownSample);

    $('#deal_coupon_text').change(function(){
      var val = $(this).val();
      $('#deal_sample_tweet').val('I just got ' + val + ' from @<%= current_authorized_user.username %>. Get yours here: ');
      updateCountdownSample();
    });    
    
  });
  
</script>

app/views/deals/_images.html.erb
<% if images.any? %>
  <p>Or pick from some you have already uploaded.</p>
<% else %>
  <p>Don't have a great image? No worries. Pick from some of our great ones!</p>
<% end %>
<ul class="images_to_select">
  <% if images.any? %>
    <% images.each do |image| %>
      <li>
        <%= image_tag image.image_url, id: "bg_image_#{image.id}" %>
        <p><%= link_to 'Preview', '#', class: 'preview' %> | <%= link_to 'Select', '#', class: 'select' %></p>
      </li>
    <% end %>
    <p>Don't have a great image? No worries. Pick from some of our great ones!</p>
    <li>
      <%= image_tag 'bg_bar2.jpg', id: 'bg_image_1' %>
      <p><%= link_to 'Preview', '#', class: 'preview' %> | <%= link_to 'Select', '#', class: 'select' %></p>
    </li>
  <% else %>
    <li>
      <%= image_tag 'bg_bar2.jpg', id: 'bg_image_1' %>
      <p><%= link_to 'Preview', '#', class: 'preview' %> | <%= link_to 'Select', '#', class: 'select' %></p>
    </li>
  <% end %>
</ul>

app/views/deals/deal.html.erb
<div class="deal_container">
	<div class="deal_inner">
		<h1>Intelligentsia Coffee</h1>
		<h2>Free 1oz Coffee</h2>
		<p>Intelligentsia is the most excellent coffee shop in the world. Just share this deal with your friends and you'll get a free 1oz coffee on your next visit to one of our super-cool shops. Your 1oz coffee features individually picked beans from around the world. Each cup contains 2 beans from Africa, 4 beans from Brazil, and 2 Folgers beans to mellow out the taste. You'll see why people pay $40 for our coffee.</p>
		<%= link_to 'Tweet to get this Deal', '/auth/twitter', class: 'tweet_btn' %>
	</div>
</div>


<script>
  $.backstretch("<%= image_path 'bg_coffee_shop.jpeg' %>");
</script>

app/views/deals/edit.html.erb
<div class="background_image_form_container">
  <h2>Edit your Deal</h2>
  <div class="change_background">
    <%= link_to 'Change background image', '', id: 'background_image_link' %>
  </div>
</div>
<div class="deal_container hide">
  <div class="background_image_selection">
    <%= render 'background' %>
  </div>
</div>

<div class="deal_container">
	<div class="deal_inner deal_details">
    <h1><%= current_authorized_user.business_name %></h1>
    <%= render 'form' %>
	</div>
</div>

<script>
  
  $(function(){

    $.backstretch("<%= @deal.image.image_url %>");
    $("#deal_end_date").datepicker({ dateFormat: 'yy-mm-dd', constrainInput: true, minDate: new Date(), defaultDate: '<%= @deal.end_date.strftime("%Y-%-m-%-e") %>' });
    
    $('#background_image_link').click(function(){
      $('.background_image_form_container').slideUp();
      $('.background_image_selection').parent().show();
      return false;
    });

    $('.preview').click(function(){
        $('.backstretch').remove();
        var url = $(this).parent().parent().children(':first-child').attr('src');
        $.backstretch(url);
        return false;
    });

    $('.select').click(function(){
      $('.backstretch').remove();
      var url = $(this).parent().parent().children(':first-child').attr('src');
      var image_id = $(this).parent().parent().children(':first-child').attr('id').toString().match(/\d+/)[0];
      $.backstretch(url);
      $('.background_image_selection').parent().slideUp();
      $('.background_image_form_container').slideDown();
      $('#deal_image_id').val(image_id);
      return false;
    });

  });
  
</script>

app/views/deals/index.html.erb
<div class="all_deals">
  <h2>
    My Deals
  </h2>
  <%= link_to 'New Deal', new_deal_path, class: 'new_btn' %>
  <table class="table">
    <tr>
      <th>Coupon</th>
      <th>New Twitter Reach</th>
      <th>Coupons Earned</th>
      <th>Coupons Redeemed</th>
      <th>% Redeemed</th>
      <th>End date</th>
      <th></th>
    </tr>

  <% @deals.each do |deal| %>
    <tr>
      <td><%= link_to deal.coupon_text, deal_url(deal) %></td>
      <td>
        <%= deal.followers %>
        <!-- <div class="progress">
          <div class="bar" style="width: <%#=  number_to_percentage((deal.followers / @deals_total_followers) * 100) %>%;">
            <p></p>
          </div>
        </div> -->
      </td>
      <td><%= deal.coupons.length %></td>
      <td><%= deal.redemptions %></td>
      <td><%= number_to_percentage(deal.conversion, precision: 0) %></td>
      <td><%= deal.end_date.strftime('%D') if deal.end_date %></td>
      <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/deals/new.html.erb
<div class="background_image_form_container hide">
  <h2>Create your Deal</h2>
  <div class="change_background">
    <%= link_to 'Change background image', '', id: 'background_image_link' %>
  </div>
</div>

<div class="deal_container">
  <div class="background_image_selection">
    <h3 id="myModalLabel">Let's start a new deal</h3>
    <%= render 'background' %>
  </div>
</div>

<script>

  $(function(){

    $('#background_image_link').click(function(){
      $('.deal_details_container').slideUp();
      $('.background_image_form_container').slideUp();
      $('.background_image_selection').delay(500).show();
      return false;
    });

    $("#deal_end_date").datepicker({ dateFormat: 'yy-mm-dd', constrainInput: true, minDate: new Date() });

    $('.preview').click(function(){
        $('.backstretch').remove();
        var url = $(this).parent().parent().children(':first-child').attr('src');
        $.backstretch(url);
        return false;
    });

    $('.select').click(function(){
      $('.backstretch').remove();
      var url = $(this).parent().parent().children(':first-child').attr('src');
      var image_id = $(this).parent().parent().children(':first-child').attr('id').toString().match(/\d+/)[0];
      $.backstretch(url);
      $('.background_image_selection').slideUp();
      $('.deal_details_container').delay(500).show();
      $('.background_image_form_container').slideDown();
      $('#deal_image_id').val(image_id);
      return false;
    });

    $('#new_deal').submit(function(){
      if ($('#deal_coupon_text').val() != '' && $('#deal_description').val() != '' && $('#deal_end_date').val() != '' && $('#deal_sample_tweet').val() != '' ){
        $.ajax({ type: 'POST', url: '<%= j(deals_url) %>',
            data: { deal: { coupon_text: $('#deal_coupon_text').val(),
                    description: $('#deal_description').val(),
                    end_date: $('#deal_end_date').val(),
                    sample_tweet: $('#deal_sample_tweet').val(),
                    image_id: $('#deal_image_id').val() }
                  },
            success: function(data){
              $('.deal_details').slideUp();
              $('.deal_starter_tweet').slideDown();
              $('.background_image_form_container').slideUp();
              $('#tweet').val('We\'re offering ' + data["coupon_text"] + '. Get yours here: <%= "#{root_url}deals/" %>' + data["id"]);
              $('#tweet').focus();
            },
            error: function(data){
              alert('Something went wrong!');
            },
        dataType: 'json'});
      }
      else {
        alert('All fields are required!\nPlease fill them all out.');
      }
      return false;
    });

  });

</script>

app/views/deals/show.html.erb
<div class="deal_container">
	<div class="deal_inner">
		<h1><%= @deal.advertiser.business_name %></h1>
		<h2><%= @deal.coupon_text %></h2>		
    <p><%= @deal.description %></p>
    <p>This deal expires on <%= @deal.end_date.strftime('%B %e, %Y') %>.</p>
        
		<% if @coupon %>
      <% if @coupon.not_redeemed? && @deal.not_expired? %>
        <p>Congratulations! You got this deal!</p>
        <p>Show this to <%= @deal.advertiser.business_name %> when you are ready to redeem it.</p>
        <p><%= link_to 'Redeem in store', coupon_url(@coupon, redeemed: true), class: 'orange_btn redeem_btn', method: :put, confirm: 'WAIT! Only continue if asked to do so by the business. The redeem button can only be pressed once. Are you sure you want to continue?' %></p>
      <% elsif @coupon.redeemed? %>
        <p>Thanks for using this coupon on <%= @coupon.updated_at.strftime('%B %e, %Y') %></p>
      <% else %>
        <p>Sorry. This deal expired on <%= @deal.end_date.strftime('%B %e, %Y') %></p>
      <% end %>
    <% elsif session[:uid] %>
      <p class="send_tweet">Send a tweet to get this deal</p>
      <%= form_tag(coupons_url) do %>
        <%= text_area_tag :tweet, "#{@deal.sample_tweet} #{deal_url(@deal, referred: true)}" %>
        <%= hidden_field_tag :deal_id, @deal.id %>
        <div class="countdown">140</div>
        <%= submit_tag 'Tweet', id: 'tweet_button' %>
      <% end %>
    <% else %>
      <p class="send_tweet">Sign in to Twitter to get this deal</p>
      <p><%= link_to 'Sign in with Twitter', '/auth/twitter', class: 'signin_btn' %></p>
    <% end %>
	</div>
</div>

<script>

  $(function(){

    $.backstretch("<%= @deal.image.image_url %>");

    $('#tweet').focus();

    function createSelection(start, end, field) {
        // if ( field.createTextRange ) {
        //   var newend = end - start;
        //   var selRange = field.createTextRange();
        //   selRange.collapse(true);
        //   selRange.moveStart("character", start);
        //   selRange.moveEnd("character", newend);
        //   selRange.select();
        // }
        // else if( field.setSelectionRange ){
        //   field.setSelectionRange(start, end);
        // }
        // field.focus();
    }

    var target = document.getElementById('tweet');
    createSelection(0, <%= @deal.sample_tweet.length %>, target);

    function updateCountdown() {
      // 140 is the max message length
      var remaining = 140 - $('#tweet').val().length;
      if (remaining <= 10){
        $('.countdown').css('color', 'red');
      }
      else {
        $('.countdown').css('color', 'white');
      }
      if (remaining < 0){
        $('#tweet_button').attr('disabled', 'disabled');
      }
      else {
        $('#tweet_button').removeAttr('disabled');
      }
      $('.countdown').text(remaining);
    }
    updateCountdown();
    $('#tweet').change(updateCountdown);
    $('#tweet').keyup(updateCountdown);
  })

</script>

app/views/deals/stats.html.erb
<div class="deal_stats">
  <h2>Deal: <%= @deal.id %></h2>
  <p><%= @deal.coupon_text %></p>
  <div class="row span12">
    <div class="well span2">
      <p>Conversion:</p>
      <p class="percentage"><b><%= number_to_percentage(@deal.conversion, precision: 0) %></b></p>
      <p><%= @deal.coupons.redeemed.length %> / <%= @deal.coupons.length %></p>
      <br/>
      <p>Seen by:</p>
      <p class="followers"><b><%= @deal.followers %></b></p>
      <p>people</p>
      <br/>
      <p>Referrals:</p>
      <p class="followers"><b><%= @deal.referrals %></b></p>
    </div>
    <div class="well span8">
      <%= high_chart("Followers", @h) %>
    </div>
  </div>
</div>