config/routes.rb
Potofgold::Application.routes.draw do

  resources :images

  resources :coupons

  resources :deals

  root :to => 'pages#home'
  get '/auth/twitter/callback' => 'sessions#create'
  delete '/signout' => 'sessions#destroy', as: :signout
  get '/deal_stats/:id' => 'deals#stats', as: :deal_stats
  post '/tweet' => 'deals#tweet', as: :tweet
  get 'advertiser_sign_in' => 'sessions#advertiser_sign_in'

  post '/redeem/:id' => 'coupons#redeem', as: :redeem

end

app/models/image.rb
class Image < ActiveRecord::Base
  
  attr_accessible :image_url, :advertiser_id
  
  #Associations
  has_many :deals
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_filter :check_current_authorized_user_is_an_advertiser

  # POST /images
  # POST /images.json
  def create
    @image = current_authorized_user.images.new(params[:image])

    respond_to do |format|
      if @image.save
        format.js
      else
        format.js
      end
    end
  end

  private

    def check_current_authorized_user_is_an_advertiser
      redirect_to root_url unless current_authorized_user.advertiser? 
    end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/create.js.erb
$('.backstretch').remove();
$.backstretch("<%= j(@image.image_url) %>");
$('.background_image_selection').slideUp();
$('.deal_details_container').delay(1000).slideDown('slow');
$('#deal_image_id').val('<%= @image.id %>');
$('.background_image_form_container').slideDown();
$('#background_image_form').slideUp();

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <tr>
    <th>Image url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= image.image_url %></td>
    <td><%= link_to 'Show', image %></td>
    <td><%= link_to 'Edit', edit_image_path(image) %></td>
    <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image url:</b>
  <%= @image.image_url %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>