config/routes.rb
Potofgold::Application.routes.draw do

  resources :images

  resources :coupons

  resources :deals

  root :to => 'pages#home'
  get '/auth/twitter/callback' => 'sessions#create'
  delete '/signout' => 'sessions#destroy', as: :signout
  get '/deal_stats/:id' => 'deals#stats', as: :deal_stats
  post '/tweet' => 'deals#tweet', as: :tweet
  get 'advertiser_sign_in' => 'sessions#advertiser_sign_in'

  post '/redeem/:id' => 'coupons#redeem', as: :redeem

end

app/views/layouts/_header.html.erb
<div class="navigation">
  <div class="navigation-inner container">
    <%= link_to "#{image_tag('bird.svg', style: 'width: 30px;')}".html_safe, root_url, class: 'logo' %>
    <ul class="navigation-links">
      <li class="twitter_handle">@<%= current_authorized_user.username %></li>
      <% if current_authorized_user.advertiser? %>
        <li class="active"><%= link_to 'My Deals', deals_url %></li>
      <% else %>
        <li class="active"><%= link_to 'My Coupons', coupons_url %></li>
      <% end %>
      <li><%= link_to 'Sign Out', signout_url, method: :delete %></li>
    </ul>
  </div>
</div>

app/views/layouts/_tracking_code.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37405841-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Go Branch Out | Share The Best Deals With Your Friends</title>
  <meta name="description" content="Share great deals from local resturants, bars, spas, and stores with your friends on Twitter." />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="//use.typekit.net/mdj3nuu.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <link rel="shortcut icon" href="/favicon.ico">
</head>
<body class="<%= controller_name -%> <%= action_name -%>">

  <% if current_authorized_user %>
    <%= render 'layouts/header' %>
  <% end %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </div>

  <%= render 'layouts/tracking_code' if Rails.env.production? %>

</body>
</html>